// <auto-generated />
namespace EntityAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migimgsize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migimgsize));
        
        string IMigrationMetadata.Id
        {
            get { return "202306211530457_mig-imgsize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
